
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  spring:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 0

google:
  api: AIzaSyAe-RvE9UpwF-SNkKvlpt4YpjOgDfaUCpQ
