server:
  port: 5001
domain:
  name: mydomain
spring:
  application:
    name: user
  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation= true
  datasource:
    platform: postgres
    url: jdbc:postgresql://gotmoversdb:5432/gotmovers
    username: postgres
    password: postgres

  cloud:
    consul:
      port: 8500
      host: consul
      discovery:
        health-check-interval: 10s
        health-check-path: /heartbeat
    gateway:
      discovery:
        locator:
          enabled: true

  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672
    dynamic: true

logging:
  level:
    org.springframework: INFO





